### ISSUE TITLE
deploy Error with solo-chain 0.0.3

### ISSUE THREAD

**Issue by JeanoLee** [punicasuite/punica-python#71]
Hi.

OS : MacOSX 10.14.2
python : 3.7v
punica : 0.0.22
solo-chain : 0.0.3

Now I'm trying to deploy sample contract on solo-chain.
But it returned error massage.

(python3.7) Jinhoui-MacBook-Pro:ontol-test jinholee$ punica deploy
Using network 'privateNet'.

An error occur...
(59000, 'Other Error, unknow contract')
(python3.7) Jinhoui-MacBook-Pro:

there are my commands for test

$ mkdir ontology-test
$ cd ontology-test
$ punica init
$ punica compile
$ punica deploy

What's wrong?

**Comment by NashMiao** [comment]
The commands you use is correct. But the information seems strange. In fact, this information means the contract didn't find in your `private network`(solo-chain). So, could you provider me the screenshot in your solo-chain's `contracts` tab?

**Comment by hero5512** [comment]
I also encounter the same problem with him.

**Comment by hero5512** [comment]
I run the Example tutorialtoken step by step. However, when I run the "punica deploy" command, I encounter the following errors:

**Using network 'privateNet'.

An error occur...
(59000, 'Other Error, unknow contract')**

**Comment by NashMiao** [comment]
@hero5512 Can you provide me the screenshot in your solo-chain's `contracts` tab?

**Comment by hero5512** [comment]
> @hero5512 Can you provide me the screenshot in your solo-chain's `contracts` tab?

![图片 1](https://user-images.githubusercontent.com/10353921/55458182-d1c70700-561e-11e9-8c65-5889b24b66b7.png)

**Comment by NashMiao** [comment]
@hero5512 Thanks, I will check out this problem right away.

**Comment by NashMiao** [comment]
@hero5512 Can you run `pip list` to show me the version of the `ontology-python-sdk` you installed?

**Comment by hero5512** [comment]
These are my installed packages.
![图片 1](https://user-images.githubusercontent.com/10353921/55467055-0ba20880-5633-11e9-9256-ecd33ae6fc68.png)

**Comment by NashMiao** [comment]
Thanks, I'm trying to fix this bug.

**Comment by NashMiao** [comment]
@hero5512 @JeanoLee Sorry for delay. Now, punica v0.0.1 has released, you can use it with newest ontology-python-sdk. Maybe you can try to use it with our `tutorialtoken-box`.

```
pip3 install punica
punica unbox tutorialtoken
```
