### ISSUE TITLE
Ontology Python SDK version does not work

### ISSUE THREAD

**Issue by carolkng** [punicasuite/punica-python#74]
In [`requirements.txt`](https://github.com/punicasuite/punica-python/blob/master/requirements.txt#L5), the version of `ontology-python-sdk` required is 2.0.2. 

However, punica-cli still relies on the `ontology.ont_sdk` import ([example](https://github.com/punicasuite/punica-python/blob/6fe791e4fa90daf0310f819b0c6c1bfa145c6c66/punica/deploy/deploy_contract.py#L9)), which is not present in new versions starting with [2.0.0](https://github.com/ontio/ontology-python-sdk/tree/v2.0.0/ontology). The latest working version is 1.3.1, so manually installing that version of the Python SDK allows Punica to continue working as expected.

Resultant error:
```
$ punica
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/bin/punica", line 6, in <module>
    from punica.cli import main
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/punica/cli/__init__.py", line 5, in <module>
    from .deploy_cmd import deploy_cmd
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/punica/cli/deploy_cmd.py", line 10, in <module>
    from punica.deploy.deploy_contract import Deploy
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/punica/deploy/deploy_contract.py", line 9, in <module>
    from ontology.ont_sdk import OntologySdk
ModuleNotFoundError: No module named 'ontology.ont_sdk'
```

**Comment by NashMiao** [comment]
@carolkng sorry, I'm still refactor the code. After all UT passed, I will publish a new release version. currently, punica-ts is an option, you can.get it by using npm.

**Comment by Kyona776** [comment]
hey just change these in deploy_contract.py, invoke_contract.py, account.py, asset.py
from ontology.ont_sdk import OntologySdk
to
from ontology.sdk import Ontology

from ontology.contract.neo.abi.abi_info import AbiInfo
from ontology.contract.neo.abi.build_params import BuildParams
from ontology.contract.neo.vm import NeoVm
to
from ontology.contract.neo.abi.abi_info import AbiInfo
from ontology.contract.neo.abi.build_params import BuildParams
from ontology.contract.neo.vm import NeoVm

**Comment by NashMiao** [comment]
@carolkng Sorry for delay. Now, punica v0.0.1 has released, you can use it with newest ontology-python-sdk. Maybe you can try to use it with our `tutorialtoken-box`.

```
pip3 install punica
punica unbox tutorialtoken
```
